In [111]:
from assoc_scan import AssocScan

In [112]:
ass_scan = AssocScan(use_accelerated=False)

In [113]:
import torch

In [114]:
b, s, d = 1, 2, 3

In [115]:
x = torch.randn((b,s,d))

In [116]:
x[0, 0] = -1e9

In [117]:
x

tensor([[[-1.0000e+09, -1.0000e+09, -1.0000e+09],
         [ 4.3091e-01, -1.0117e+00, -4.8157e-01]]])

In [118]:
gates = torch.tensor([1,0.0])

In [119]:
ass_scan(gates, x)

tensor([[[-1.0000e+09, -1.0000e+09, -1.0000e+09],
         [ 4.3091e-01, -1.0117e+00, -4.8157e-01]]])

In [120]:
p = torch.tensor([0, 1])

In [121]:
from torch.nn.functional import pad

In [122]:
pad_p = pad(p, (1, 0), value = 1)

In [123]:
pl = torch.ones(d)

In [124]:
keys = torch.randn((1, s, d))

In [125]:
from einops import repeat

In [126]:
start_keys = repeat(pl, 'd -> b 1 d', b = 1)

In [127]:
keys = torch.cat([start_keys, keys], dim=1)

In [128]:
keys

tensor([[[ 1.0000,  1.0000,  1.0000],
         [-0.1717, -0.0144,  0.2643],
         [ 0.2310, -0.8723, -1.3921]]])

In [129]:
keys[:, pad_p == 1] = pl

In [130]:
keys

tensor([[[ 1.0000,  1.0000,  1.0000],
         [-0.1717, -0.0144,  0.2643],
         [ 1.0000,  1.0000,  1.0000]]])

In [131]:
keys = torch.tensor([[
         [ 6.6796e-04,  1.0707e-02], # keep
         [ 1.2260e+00, -1.0057e+00], # keep
         [ 2.7146e-01, -5.9301e-01], # discard
         [ 6.6796e-04,  1.0707e-02], # keep
         [-4.1065e-01,  6.2196e-01]  # keep
]])

In [132]:
m = torch.tensor([0, 0, 1, 0])

In [133]:
m2 = pad(m, (0, 1), value=0)

In [134]:
keys = keys[:, m2 != 1]
keys

tensor([[[ 6.6796e-04,  1.0707e-02],
         [ 1.2260e+00, -1.0057e+00],
         [ 6.6796e-04,  1.0707e-02],
         [-4.1065e-01,  6.2196e-01]]])

In [ ]:
boundary probs: tensor([[5.5319e-01, 9.9487e-01],
        [1.0878e-05, 8.9463e-01],
        [1.3683e-01, 5.5906e-01]], grad_fn=<ToPaddedTensorBackward0>)
downsampled tokens: tensor([[[ 3.3987e-01,  4.6595e-01,  1.8461e-01,  1.2003e+00,  1.7549e-01,
           4.0810e-01],
         [-4.3039e-02,  1.5487e+00, -4.2201e-01, -7.4840e-01,  4.9490e-01,
           1.1368e-01]],

        [[-1.6289e-05,  1.3337e-06,  5.0730e-06,  9.9005e-07,  1.3297e-05,
          -1.0687e-05],
         [-1.4945e+00, -1.2153e+00, -1.4739e-01, -4.3173e-01,  7.0506e-02,
          -4.7886e-02]],

        [[-6.9309e-02,  1.1804e-01,  3.3555e-02,  1.2978e-01,  4.7402e-02,
          -1.8877e-01],
         [ 8.7156e-01,  2.0464e-01, -2.8968e-01,  2.4440e-01,  7.3751e-01,
          -3.2294e-01]]], grad_fn=<MulBackward0>)