In [1]:
import torch
from h_net_dynamic_chunking import DynamicSequenceChunker

In [2]:
batch, seq, dim = 4, 10, 6
tokens = torch.randn(batch, seq, dim)

### Pack Chunker

In [3]:
# following section 2.2 of the paper

from collections import namedtuple

import torch
from torch import cat, arange
from torch.nested import nested_tensor
from torch.nn import Module, Linear, Parameter
from torch.nn.functional import cosine_similarity, pad
from torch.nn.utils.rnn import pad_sequence

from einx import multiply
from einops import repeat, rearrange

from assoc_scan import AssocScan

# constants

Outputs = namedtuple('Outputs', [
    'downsampled',
    'upsample_fn',
    'weighted_aux_ratio_loss'
])

Intermediates = namedtuple('Intermediates', [
    'mask',
    'probs',
    'chunk_lens',
    'boundary_mask',
    'residual',
    'gates',
    'upsampler_output_scale',
    'aux_ratio_loss',
    'input_mask',     # Added: needed to handle padding logic in upsampler
    'is_packed',      # Added: to track state
    'seq_lens',       # Added: original sequence lengths
    'new_seq_lens'    # Added: downsampled sequence lengths
])

# helper functions

def exists(v):
    return v is not None

def default(v, d):
    return v if exists(v) else d

def straight_through(t, value):
    return t + (value - t).detach()

def frac_gradient(t, frac = 1.):
    if frac == 1:
        return

    t_grad = t * frac
    return straight_through(t_grad, t)

# classes

class PackDynamicSequenceChunker(Module):
    def __init__(
        self,
        dim,
        dim_queries_keys = None,
        boundary_threshold = 0.5,
        target_avg_token_length = 6.,       # N in eq(10)
        ratio_loss_weight = 3e-2,
        handle_residual_proj = False,       # turning this on will automatically handle a projection of the residual and its application in the inverse upsample function
        assoc_scan_use_accelerated = False,
        learning_rate_difference = 0.75,    # in the paper, they report that as one moves up a hierarchy, the learning rate needs to decrease. we'll default to 0.75 for the rough 2.0 -> 1.5 somewhere in the appendix from level 0 -> 1
        straight_through_frac_vecs = True,  # improvisation where F receives gradients through straight-through with sigmoid
    ):
        super().__init__()
        dim_queries_keys = default(dim_queries_keys, dim)

        # linear to queries and keys

        self.to_queries_keys = Linear(dim, dim_queries_keys * 2, bias = False)

        # start key token, so first token can be segmented / chunked out

        self.start_key_token = Parameter(torch.randn(dim_queries_keys) * 1e-2) # presumably, need a start key token for the first token, open an issue if i got it wrong

        # threshold to determine boundary

        assert 0. < boundary_threshold < 1.

        self.boundary_threshold = boundary_threshold

        # smoothing related

        self.smooth_assoc_scan = AssocScan(use_accelerated = assoc_scan_use_accelerated)

        # maybe residual proj

        self.handle_residual_proj = handle_residual_proj

        if handle_residual_proj:
            self.residual_proj = Linear(dim, dim)

        # learning rate modulation, appendix C
        # the multiplier on the learning rate as one goes from outer to inner of the h-net, and inverse of this value from inner to outer

        self.learning_rate_difference = learning_rate_difference

        # ratio aux loss related

        self.target_avg_token_length = target_avg_token_length

        self.straight_through_frac_vecs = straight_through_frac_vecs

        self.ratio_loss_weight = ratio_loss_weight

        self.register_buffer('zero', torch.tensor(0.), persistent = False)

    def upsample(
        self,
        downsampled,
        intermediates: Intermediates,
        apply_scale = True
    ):
        # handle packed sequence input for upsampling
        is_packed = downsampled.ndim == 2
        
        if is_packed:
            # If the original input was packed, the downsampled input here should be packed.
            # We need to unpack it to (B, N, D) to use the internal logic.
            assert exists(intermediates.new_seq_lens), "Cannot upsample packed sequence without new_seq_lens"
            downsampled_list = list(downsampled.split(intermediates.new_seq_lens.tolist()))
            downsampled = pad_sequence(downsampled_list, batch_first=True)

        batch, needs_grad, device = downsampled.shape[0], downsampled.requires_grad, downsampled.device

        mask = intermediates.mask
        gates = intermediates.gates
        residual = intermediates.residual

        # smoothing module for improved gradients eq(5)

        downsampled = self.smooth_assoc_scan(gates, downsampled)

        # upsample

        downsampled_without_padding = downsampled[mask]
        chunk_lens_without_padding = intermediates.chunk_lens[mask]

        seq = arange(downsampled_without_padding.shape[0], device = device)

        repeated_indices = torch.repeat_interleave(seq, chunk_lens_without_padding, dim = 0)
        upsampled = downsampled_without_padding[repeated_indices]

        upsampled = rearrange(upsampled, '(b n) d -> b n d', b = batch)

        scale = intermediates.upsampler_output_scale

        if needs_grad and apply_scale and exists(scale):
            upsampled = multiply('b n d, b n', upsampled, scale)

        if self.handle_residual_proj:
            # We need to use the original residual (input tokens)
            # If we are in packed mode, the residual stored in intermediates is likely padded.
            # We apply the projection on the padded residual and mask later if needed.
            upsampled = upsampled + self.residual_proj(residual)

        upsampled = frac_gradient(upsampled, self.learning_rate_difference)
        
        # If the original input was packed, we must return a packed sequence.
        # We use the original sequence lengths from intermediates to repack.
        if intermediates.is_packed:
            # Mask out padding from the padded upsampled result
            # intermediates.input_mask contains the valid locations of the original sequence
            if exists(intermediates.input_mask):
                upsampled = upsampled[intermediates.input_mask]
            else:
                # Fallback if mask missing (shouldn't happen in packed flow)
                upsampled_list = [upsampled[i, :l] for i, l in enumerate(intermediates.seq_lens)]
                upsampled = cat(upsampled_list, dim=0)

        return upsampled

    def forward(
        self,
        tokens, # float[b n d] OR float[total_n d] if packed
        seq_lens = None, # Required if tokens is packed
        return_intermediates = False,
        return_only_chunk_lens = False
    ):
        # ----------------------------------------------------------------------
        # Handle Packed Sequences
        # ----------------------------------------------------------------------
        is_packed = tokens.ndim == 2
        input_mask = None
        
        if is_packed:
            assert exists(seq_lens), 'seq_lens must be provided for packed sequences'
            # Unpack to (Batch, MaxLen, Dim) for processing
            tokens_list = list(tokens.split(seq_lens.tolist()))
            tokens_padded = pad_sequence(tokens_list, batch_first=True)
            
            # Create mask for padding
            # This is critical for cosine_sim and loss masking
            max_len = tokens_padded.shape[1]
            batch_size = len(seq_lens)
            range_tensor = arange(max_len, device=tokens.device).expand(batch_size, max_len)
            input_mask = range_tensor < seq_lens.unsqueeze(1)
            
            # Switch tokens pointer to padded version
            tokens = tokens_padded
        else:
            # Standard batched input
            # Create a default mask of all True if not provided
            batch, length = tokens.shape[:2]
            input_mask = torch.ones((batch, length), device=tokens.device, dtype=torch.bool)
            seq_lens = torch.full((batch,), length, device=tokens.device, dtype=torch.long)

        batch, length, device = *tokens.shape[:2], tokens.device

        residual = tokens

        queries, keys = self.to_queries_keys(tokens).chunk(2, dim = -1)

        start_keys = repeat(self.start_key_token, 'd -> b 1 d', b = batch)

        keys = cat((start_keys, keys), dim = 1)

        # each query looks at the previous key
        # Handle padding for cosine similarity: avoid NaN by adding epsilon to norms or masking
        
        keys_shifted = keys[:, :-1]
        
        # Safe cosine similarity
        eps = 1e-6
        queries_norm = queries.norm(dim=-1, keepdim=True)
        keys_norm = keys_shifted.norm(dim=-1, keepdim=True)
        numerator = (queries * keys_shifted).sum(dim=-1)
        denominator = (queries_norm * keys_norm).clamp(min=eps).squeeze(-1)
        cosine_sim = numerator / denominator

        # Mask out cosine sim on padding to avoid garbage boundaries
        cosine_sim = cosine_sim.masked_fill(~input_mask, 1.0) # 1.0 sim -> 0.0 prob -> no boundary

        probs = (1. - cosine_sim) * 0.5 # cosine sim is -1. to 1., this transforms it to 0. to 1.

        boundary_mask = probs > self.boundary_threshold # bool[b n]

        boundary_mask[:, 0] = True # first token must always be boundary
        
        # Ensure padding tokens are never boundaries
        boundary_mask = boundary_mask & input_mask

        # compute some lengths, per chunk and number of chunks per batch

        num_chunks = boundary_mask.long().sum(dim = -1)

        boundary_mask_with_end = pad(boundary_mask, (0, 1), value = True)
        sel_indices = repeat(arange(boundary_mask_with_end.shape[-1], device = device), 'n -> b n', b = batch)[boundary_mask_with_end]

        sel_indices = nested_tensor(sel_indices.split((num_chunks + 1).tolist()), layout = torch.jagged, device = device)

        sel_indices = sel_indices.to_padded_tensor(padding = -1)

        mask = (sel_indices != -1)[:, 1:]

        chunk_lens = sel_indices[:, 1:] - sel_indices[:, :-1]
        chunk_lens.masked_fill_(~mask, 0)

        # early return chunk lens if using a trained module as a tokenizer

        if return_only_chunk_lens:
            if is_packed:
                # Return packed chunk lenses
                return chunk_lens[mask]
            return chunk_lens

        # downsampling - they show in their experiments that picking out the boundary tokens works just fine

        boundary_tokens = tokens[boundary_mask] # pick out boundary tokens

        tokens_nt = nested_tensor(boundary_tokens.split(num_chunks.tolist()), layout = torch.jagged, device = device, requires_grad = True)

        downsampled_tokens = tokens_nt.to_padded_tensor(padding = 0.)

        # smoothing module for improved gradients eq(5)

        probs_nt = nested_tensor(probs[boundary_mask].split(num_chunks.tolist()), layout = torch.jagged, device = device, requires_grad = True)

        boundary_probs = probs_nt.to_padded_tensor(padding = 0.)

        gates = 1. - boundary_probs

        downsampled_tokens = multiply('b n d, b n', downsampled_tokens, boundary_probs)

        # for the upsampler

        confidence = torch.where(boundary_mask, probs, 1. - probs)

        # defaults if not training

        upsampler_output_scale = None
        aux_loss = self.zero
        weighted_aux_loss = self.zero

        needs_grad = tokens.requires_grad

        if needs_grad:
            # straight through for 1. multiplier on the expanded processed boundary tokens
            
            # For scale, we only care about valid tokens
            if is_packed:
                upsampler_output_scale = straight_through(confidence, 1.) # Padded shape
                # We don't mask here because multiply() in upsampler handles shape, 
                # but valid gradients only come from valid indices.
            else:
                upsampler_output_scale = straight_through(confidence, 1.)

            # auxiliary ratio loss in section 2.3.2, eq (10)

            N = self.target_avg_token_length

            F = boundary_mask.float()
            
            # Mask the probs for G calculation so padding doesn't affect mean
            probs_masked = probs * input_mask.float()
            G = probs_masked.sum(dim = -1) / input_mask.float().sum(dim = -1).clamp(min=1.)

            # allow for a soft F to straight through - https://arxiv.org/abs/2505.22074

            if self.straight_through_frac_vecs:
                F_soft = (probs - self.boundary_threshold).sigmoid()
                F = straight_through(F_soft, F)

            # Mask F for mean calculation
            F = (F * input_mask.float()).sum(dim = -1) / input_mask.float().sum(dim = -1).clamp(min=1.)

            aux_ratio_loss = N / (N - 1) * ((N - 1) * F * G + (1. - F) * (1. - G))

            aux_loss = aux_ratio_loss.mean()
            weighted_aux_loss = aux_loss * self.ratio_loss_weight

        # intermediates
        
        # Calculate new seq lengths for packed return
        new_seq_lens = num_chunks
        
        intermediates = Intermediates(
            mask, probs, chunk_lens, boundary_mask, residual, gates, 
            upsampler_output_scale, aux_loss,
            input_mask, is_packed, seq_lens, new_seq_lens
        )

        # return the upsample function

        def upsample(downsampled, apply_scale = True):
            return self.upsample(downsampled, intermediates, apply_scale = apply_scale)

        # adjust learning rate

        downsampled_tokens = frac_gradient(downsampled_tokens, self.learning_rate_difference ** -1)

        # handle packed output
        
        if is_packed:
            # We computed downsampled_tokens as (B, N_chunks, D) padded.
            # We need to pack it back to (Total_Chunks, D)
            # We can use new_seq_lens (num_chunks) to create the mask for valid data
            valid_chunks_mask = arange(downsampled_tokens.shape[1], device=device).expand(batch, -1) < new_seq_lens.unsqueeze(1)
            downsampled_tokens = downsampled_tokens[valid_chunks_mask]

        # returning

        outputs = Outputs(downsampled_tokens, upsample, weighted_aux_loss)

        if not return_intermediates:
            return outputs

        return outputs, intermediates

### Testing

In [4]:
chunker = PackDynamicSequenceChunker(dim=dim)

In [5]:
output, intermediates = chunker(tokens, return_intermediates=True)

In [6]:
downsampled = output.downsampled
upsample_fn = output.upsample_fn

In [7]:
assert upsample_fn(downsampled).shape == tokens.shape
upsampled = upsample_fn(downsampled)

In [8]:
# we'll try packing the tokens into a 2d tensor
packed_tokens = tokens.view(-1, dim)
seq_lens = torch.full((batch,), seq, dtype=torch.long)

In [9]:
packed_output, packed_intermediates = chunker(packed_tokens, seq_lens=seq_lens, return_intermediates=True)

In [10]:
packed_downsampled = packed_output.downsampled
packed_upsample_fn = packed_output.upsample_fn

In [11]:
packed_upsampled = packed_upsample_fn(packed_downsampled)

In [12]:
packed_upsampled = packed_upsampled.view(batch, seq, dim)

In [13]:
torch.allclose(upsampled, packed_upsampled)

True

### More Testing

In [14]:
import random
tokens = []
for _ in range(batch):
    length = random.randint(5, 15)
    tokens.append(torch.randn(length, dim))

In [15]:
seq_lens = torch.tensor([t.shape[0] for t in tokens], dtype=torch.long)

In [16]:
sum(seq_lens)

tensor(46)

In [17]:
packed_tokens = cat(tokens, dim=0)

In [18]:
packed_tokens.requires_grad_(True)

tensor([[-0.2811, -0.0183, -0.7339,  1.3912, -0.0349,  2.0000],
        [-1.6068,  1.2719,  0.6986, -0.1323,  0.1171,  0.2591],
        [ 0.2812,  2.1973, -0.5555, -0.1148, -0.3636,  1.5843],
        [ 0.6419,  0.7335,  0.5826, -1.4516, -0.2430, -1.3605],
        [ 0.8433,  0.2756, -0.0368,  0.1933, -0.4746,  0.1494],
        [-1.0968,  1.1501, -0.6996,  0.4604,  2.6526, -1.3864],
        [ 0.5884,  0.5012, -0.8607, -0.4995,  1.7886,  0.1358],
        [ 0.5600,  1.8541,  0.1609, -0.2951,  1.8283, -1.4094],
        [ 0.3431, -0.9126,  0.1970, -0.0537,  0.6012, -0.2392],
        [-0.6882, -0.2753, -0.4516,  0.9160,  0.0528,  0.2800],
        [ 0.3801,  0.3738,  1.3966,  0.0368,  1.0898, -0.7166],
        [ 0.5416, -0.9451, -0.2158,  0.6629, -1.5498, -0.3925],
        [-1.1886, -0.2104,  1.9907, -0.6726,  0.0207,  0.0789],
        [ 0.8497,  0.4604,  1.0230, -1.3509, -1.6907,  1.4050],
        [-1.9700, -0.8096, -0.1399, -1.6950, -0.7268,  0.5012],
        [-2.2096,  0.7422, -1.0403,  1.1

In [19]:
assert packed_tokens.shape == (sum(seq_lens), dim)

In [20]:
chunker = DynamicSequenceChunker(dim=dim)

In [21]:
ref_chunks = []
for t in tokens:
    out, intermediates = chunker(t.unsqueeze(0), return_intermediates=True)
    ref_chunks.append(out.downsampled.squeeze(0))

In [22]:
pack_chunker = PackDynamicSequenceChunker(dim=dim)
pack_chunker.load_state_dict(chunker.state_dict())

<All keys matched successfully>

In [23]:
packed_chunks, packed_intermediates = pack_chunker(packed_tokens, seq_lens=seq_lens, return_intermediates=True)

In [24]:
packed_intermediates.new_seq_lens

tensor([7, 4, 7, 8])

In [25]:
# if we reshape packed_chunks to a list of tensors, make it nested, pad with zeros, and compare to ref_chunks, it should be equal
split = packed_chunks.downsampled.split(packed_intermediates.new_seq_lens.tolist())

In [26]:
split

(tensor([[-0.1828, -0.0119, -0.4771,  0.9044, -0.0227,  1.3002],
         [-1.2150,  0.9617,  0.5283, -0.1001,  0.0885,  0.1959],
         [ 0.2203,  1.7217, -0.4353, -0.0899, -0.2849,  1.2414],
         [ 0.3581,  0.4092,  0.3250, -0.8098, -0.1355, -0.7590],
         [ 0.3020, -0.8034,  0.1734, -0.0472,  0.5293, -0.2106],
         [-0.3925, -0.1570, -0.2576,  0.5225,  0.0301,  0.1597],
         [ 0.2837,  0.2790,  1.0425,  0.0275,  0.8134, -0.5349]],
        grad_fn=<SplitWithSizesBackward0>),
 tensor([[-0.5576,  0.1873, -0.2625,  0.2836,  0.3786,  0.0533],
         [-0.4788, -0.7717, -0.0710,  0.5091, -1.0340,  0.0134],
         [-0.3860,  2.1308,  0.1816,  1.3300, -0.4545, -0.3480],
         [ 0.8047,  0.4115,  0.1109,  0.0710,  0.1791, -0.5599]],
        grad_fn=<SplitWithSizesBackward0>),
 tensor([[-0.1775, -0.0645, -0.0939, -0.3212,  0.0046,  0.0920],
         [-0.0763,  0.7088, -0.9967,  0.8127,  0.0329, -0.7109],
         [ 0.1348,  0.6369,  0.2630, -0.8723,  0.2338, -0.6997],


In [27]:
from torch.nested import nested_tensor, to_padded_tensor

In [28]:
ref_chunks_padded = to_padded_tensor(nested_tensor(ref_chunks), 0.0)

/media/john/Tertiary/Projects/ML/BayesianFlowNet/.venv/lib/python3.12/site-packages/torch/nested/__init__.py:250: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. We recommend specifying layout=torch.jagged when constructing a nested tensor, as this layout receives active development, has better operator coverage, and works with torch.compile. (Triggered internally at /pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  return _nested.nested_tensor(


In [29]:
split_padded = to_padded_tensor(nested_tensor(list(split)), 0.0)

In [30]:
torch.allclose(ref_chunks_padded, split_padded)

True

In [31]:
upsampled_packed = packed_chunks.upsample_fn(packed_chunks.downsampled)

In [32]:
packed_chunks.weighted_aux_ratio_loss.backward()

In [ ]:
l = upsampled_packed.mean() + packed_chunks.weighted_aux_ratio_loss

tensor(0.2170, grad_fn=<AddBackward0>)

In [71]:
l.backward()