In [32]:
import torch
import numpy as np

In [33]:
torch.manual_seed(3)

In [34]:
sigma_1 = 0.001
t = 0.99

In [35]:
gamma = sigma_1 ** t

In [36]:
gamma

0.0010715193052376064

In [37]:
ground_truth = torch.randn((1,3))

In [38]:
ground_truth

tensor([[0.8033, 0.1748, 0.0890]])

In [39]:
original_epsilon  =torch.normal(0, 1, ground_truth.shape)

In [40]:
original_epsilon

tensor([[-0.6137,  0.0462, -1.3683]])

In [41]:
gamma * (1 - gamma)

0.0010703711516161095

In [42]:
mu = gamma * ground_truth + np.sqrt(gamma * (1 - gamma)) * original_epsilon

In [43]:
mu

tensor([[-0.0192,  0.0017, -0.0447]])

In [44]:
mu / gamma - np.sqrt((1-gamma) / gamma) * original_epsilon

tensor([[0.8033, 0.1748, 0.0890]])

In [45]:
incorrect_epsilon = torch.normal(0, 1, ground_truth.shape)

In [46]:
mu / gamma - np.sqrt((1-gamma) / gamma) * incorrect_epsilon

tensor([[-28.2400, -29.2873,   2.1322]])

In [47]:
mu

tensor([[-0.0192,  0.0017, -0.0447]])