In [1]:
import torch

doc_ids = torch.tensor([[0, 0, 0, 1, 1, 1, 1, 2, 2]])

# Find where groups change
is_new_group = torch.cat([
    torch.ones_like(doc_ids[:, :1], dtype=torch.bool),
    doc_ids[:, 1:] != doc_ids[:, :-1]
], dim=1)

# Get the indices where new groups start
group_start_indices = torch.where(is_new_group)[1]

In [6]:
doc_ids.shape[-1]

9

In [3]:
is_new_group

tensor([[ True, False, False,  True, False, False, False,  True, False]])

In [7]:
torch.cat([group_start_indices, torch.tensor([doc_ids.shape[-1]])])

tensor([0, 3, 7, 9])

In [10]:
# Broadcast subtraction: subtract the start index of current group from position
positions = torch.arange(doc_ids.size(1)).unsqueeze(0).expand_as(doc_ids)
group_starts = torch.zeros_like(positions)

In [11]:
group_starts[:, is_new_group[0]] = group_start_indices

In [12]:
group_starts

tensor([[0, 0, 0, 3, 0, 0, 0, 7, 0]])

In [13]:
group_starts = group_starts.cummax(dim=1)[0]  # Forward fill the start indices

In [15]:
group_starts, positions

(tensor([[0, 0, 0, 3, 3, 3, 3, 7, 7]]), tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]))

In [16]:
positions = positions - group_starts

In [17]:
positions

tensor([[0, 1, 2, 0, 1, 2, 3, 0, 1]])

In [18]:
pos_emb  =torch.randn(5, 16) # max 5 positions, embedding dim 16

In [20]:
pos_emb[positions].shape

torch.Size([1, 9, 16])