In [25]:
import torch

In [26]:
batch_size, seq_len, K = 2, 8, 4

In [27]:
truth = torch.zeros((batch_size, seq_len, K))

In [28]:
output = torch.randn((batch_size, seq_len, K))

In [29]:
truth, output

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[ 3.4280e-01, -8.8905e-01, -2.4045e-01,  4.2762e-01],
          [-3.4934e-01,  1.1599e+00, -1.1783e+00, -1.1149e-02],
          [ 1.8625e+00,  6.3035e-01,  3.0012e-02,  4.0623e-01],
          [ 2.6041e-01, -8.7968e-02, -1.3128e+00,  1.6879e+00],
          [-1.6312e+00,  3.8992e-01,  2.3410e-01,  9.3525e-02],
          [-1.1081e+00, -8.5931e-01, -1.0951e+00, -6.2965e-01],
          [-1.5038e+00, -9.6270e-01, -3.9929e-01,  2.2019e-01],
          [-9.4426e-01, -4.9173e-01,  1.6153e+00,  1.7860e+00]],
 
         [[-2.3358e-01, -1.5992

In [30]:
indices = torch.arange(seq_len)
lower_half = indices < (seq_len // 2)
lower_half.unsqueeze(0).unsqueeze(-1).shape

torch.Size([1, 8, 1])

In [31]:
lower_half

tensor([ True,  True,  True,  True, False, False, False, False])

In [32]:
torch.where(lower_half.unsqueeze(0).unsqueeze(-1), truth, output)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-1.6312e+00,  3.8992e-01,  2.3410e-01,  9.3525e-02],
         [-1.1081e+00, -8.5931e-01, -1.0951e+00, -6.2965e-01],
         [-1.5038e+00, -9.6270e-01, -3.9929e-01,  2.2019e-01],
         [-9.4426e-01, -4.9173e-01,  1.6153e+00,  1.7860e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.4493e+00,  1.0239e+00, -6.2054e-01,  3.3346e-01],
         [-4.9711e-01,  2.9622e+00, -7.0650e-01, -7.5844e-01],
         [ 7.9525e-01, -1.0036e+00,  1.8657e-01,  4.9604e-02],
         [ 1.6201e+00, -2.9856e-02,  7.4890e-01,  1.7