In [2]:
import torch
from torch.nn import functional as F

In [14]:
batch_size = 10
alphas = torch.rand(batch_size)
t = torch.rand(batch_size)

In [15]:
alphas.shape

torch.Size([10])

In [16]:
alphas, t

(tensor([0.7072, 0.6739, 0.2351, 0.2071, 0.6069, 0.5171, 0.7781, 0.1091, 0.8064,
         0.5036]),
 tensor([0.7787, 0.9335, 0.2680, 0.9295, 0.9302, 0.1240, 0.2566, 0.7188, 0.6545,
         0.3812]))

In [18]:
# alphas and t should have one-to-one relationship, we sort t and then sort alpha accordingly
t_v, t_i = torch.sort(t)
alphas = alphas[t_i]

In [20]:
t_v, t_i, alphas

(tensor([0.1240, 0.2566, 0.2680, 0.3812, 0.6545, 0.7188, 0.7787, 0.9295, 0.9302,
         0.9335]),
 tensor([5, 6, 2, 9, 8, 7, 0, 3, 4, 1]),
 tensor([0.5171, 0.7781, 0.2351, 0.5036, 0.8064, 0.1091, 0.7072, 0.2071, 0.6069,
         0.6739]))

In [21]:
F.relu(alphas[:-1] - alphas[1:])

tensor([0.0000, 0.5430, 0.0000, 0.0000, 0.6973, 0.0000, 0.5000, 0.0000, 0.0000])