In [1]:
import torch
from torch import tensor

In [2]:
data = torch.load("../collate_error_debug.pt")

In [3]:
mask = data['mask']

In [4]:
x = data['x']

In [5]:
x

[tensor([ 35,  79, 104, 103]),
 tensor([104, 117, 104,   1]),
 tensor([102, 114, 113, 118]),
 tensor([122,  61,  35, 113]),
 tensor([104, 121, 104, 117]),
 tensor([104,  35,  80, 114]),
 tensor([104, 100, 117, 118]),
 tensor([ 42, 118,  35, 100]),
 tensor([113, 103,  35, 112]),
 tensor([ 68, 118,  35, 124]),
 tensor([105, 119, 104, 113]),
 tensor([103, 100, 112,  47]),
 tensor([114, 117, 111, 103]),
 tensor([70, 92, 61, 13]),
 tensor([ 35, 101, 104, 108]),
 tensor([120, 118,  35, 111])]

In [6]:
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(os.getcwd()), "./"))
sys.path.append(parent_dir)

In [7]:
from src.datasets.collate_fn import flow, span_masking

In [8]:
from src.tokenizers.byt5.byt5_tokenizer import ByT5Tokenizer as Tokenizer

In [9]:
tk = Tokenizer()

In [10]:
tk.enc_mask_token_id(), tk.dec_mask_token_id()

(0, 0)

In [11]:
encs, targs = [], []
for sample in x:
    enc, targ = flow(sample, mask, tk.enc_mask_token_id(), tk.dec_mask_token_id())
    encs.append(enc)
    targs.append(targ)

In [12]:
encs

[tensor([  0, 103]),
 tensor([0, 1]),
 tensor([  0, 118]),
 tensor([  0, 113]),
 tensor([  0, 117]),
 tensor([  0, 114]),
 tensor([  0, 118]),
 tensor([  0, 100]),
 tensor([  0, 112]),
 tensor([  0, 124]),
 tensor([  0, 113]),
 tensor([ 0, 47]),
 tensor([  0, 103]),
 tensor([ 0, 13]),
 tensor([  0, 108]),
 tensor([  0, 111])]

In [20]:
torch.stack(encs)

tensor([[  0, 103],
        [  0,   1],
        [  0, 118],
        [  0, 113],
        [  0, 117],
        [  0, 114],
        [  0, 118],
        [  0, 100],
        [  0, 112],
        [  0, 124],
        [  0, 113],
        [  0,  47],
        [  0, 103],
        [  0,  13],
        [  0, 108],
        [  0, 111]])